version: '3.8'

services:
  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zammad-init:
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    environment:
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=postgres
      - POSTGRESQL_DB=zammad_production
      - REDIS_URL=redis://zammad-redis:6379
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
    image: ghcr.io/zammad/zammad:6.4.1
    restart: on-failure
    volumes:
      - zammad-data:/opt/zammad

  zammad-memcached:
    image: memcached:1.6-alpine
    command: memcached -m 256M
    restart: always

  zammad-postgresql:
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zammad_production
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zammad-railsserver:
    command: ["zammad-railsserver"]
    ports:
      - "9000:3000"
    depends_on:
      - zammad-init
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
      - zammad-elasticsearch
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=postgres
      - POSTGRESQL_DB=zammad_production
      - POSTGRESQL_DB_POOL=50
      - REDIS_URL=redis://zammad-redis:6379
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SSL=false
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_SERVED_SSL_ENABLED=false
      - WEB_CONCURRENCY=4
    image: ghcr.io/zammad/zammad:6.4.1
    restart: always
    volumes:
      - zammad-data:/opt/zammad

  zammad-redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-init
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
      - zammad-railsserver
      - zammad-elasticsearch
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=postgres
      - POSTGRESQL_DB=zammad_production
      - POSTGRESQL_DB_POOL=15
      - REDIS_URL=redis://zammad-redis:6379
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
    image: ghcr.io/zammad/zammad:6.4.1
    restart: always
    volumes:
      - zammad-data:/opt/zammad

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-init
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
      - zammad-railsserver
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=postgres
      - POSTGRESQL_DB=zammad_production
      - POSTGRESQL_DB_POOL=5
      - REDIS_URL=redis://zammad-redis:6379
    image: ghcr.io/zammad/zammad:6.4.1
    restart: always
    volumes:
      - zammad-data:/opt/zammad

volumes:
  elasticsearch-data:
  postgresql-data:
  redis-data:
  zammad-data: